version: '3.8'

volumes:
    logs:
        driver: local

services:
    slim:
        image: php:7-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            - docker=true
            - ACCESS_KEY='your-access-key'
            - SECRET_KEY='your-secret-access-key'
            - ENDPOINT='endpoint-url-of-minIO-server'
            - BUCKET='bucket-name'
        ports:
            - "8080:8080"
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        networks:
            - mynetwork
networks:
    mynetwork:
        external: true
